version: "3.8"

services:
  frontend:
    image: tangilecadre/bobapp-front:latest
    container_name: bobapp-front
    ports:
      - "4200:80"
    restart: unless-stopped
    networks:
      - bobapp-network

  backend:
    image: tangilecadre/bobapp-back:latest
    container_name: bobapp-back
    ports:
      - "8081:4200"
    restart: unless-stopped
    networks:
      - bobapp-network

networks:
  bobapp-network:
    driver: bridge
