version: "3.8"

services:
  frontend:
    image: tangilecadre/bobapp-front:latest
    container_name: bobapp-front
    ports:
      - "4202:80"
    restart: unless-stopped
    networks:
      - bobapp-network

  backend:
    image: tangilecadre/bobapp-back:latest
    container_name: bobapp-back
    ports:
      - "8081:4202"
    restart: unless-stopped
    networks:
      - bobapp-network

networks:
  bobapp-network:
    driver: bridge
