version: '3.8'

services:
  frontend:
    image: tangilecadre/bobapp-front:latest
    container_name: bobapp-front
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    image: tangilecadre/bobapp-back:latest
    container_name: bobapp-back
    ports:
      - "8081:8080"
    restart: unless-stopped
