sonar.projectKey=TangiLC_OC-P10_CICD:back
sonar.projectName=Bobapp_Backend
sonar.sources=src
sonar.language=java
sonar.java.binaries=target/classes
sonar.coverageReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/node_modules/**,**/*.spec.ts
