name: Backend Build & Test
on:
  push:
    branches: [main, develop]

  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  checks: write

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java & Maven
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Build and test
        run: |
          mvn clean verify

      - name: List test reports
        run: |
          ls -la target/surefire-reports/
          echo "Test reports content:"
          cat target/surefire-reports/*.xml || echo "No XML files found"

      - name: Test Report
        if: success() || failure()
        uses: phoenix-actions/test-reporting@v8
        with:
          name: Backend Tests
          path: "**/surefire-reports/*.xml"
          reporter: java-junit
          fail-on-error: false

      - name: Upload coverage report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: back-coverage-report
          path: target/site/jacoco/

      - name: Set build status
        id: build
        run: |
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t bobapp-back .

      - name: Save Docker image
        run: docker save bobapp-back > bobapp-back.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: backend-docker-image
          path: bobapp-back.tar

      - name: Set final status
        if: always()
        run: |
          echo "final_status=${{ steps.build.outputs.status }}" >> $GITHUB_OUTPUT
