name: Backend Build and Test CI
run-name: ${{ github.actor }} | Backend Build and Test CI

on:
  push:
    branches:
      - main
      - develop
    #paths:
    #  - 'back/**'
  pull_request:
    branches:
      - main
      - develop
    #paths:
    #  - 'back/**'

jobs:
  backend-build-test:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java & Maven
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install back-end dependencies & Run tests with coverage
        run: |
          cd back
          mvn clean verify

      - name: Archive test reports (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: back/target/surefire-reports/*.xml

      - name: Backend Test Report
        uses: phoenix-actions/test-reporting@v14
        id: back-test-report
        if: success() || failure()
        with:
          name: Backend Tests
          path: back/target/surefire-reports/*.xml
          reporter: java-junit

      - name: Upload back-end coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: back-coverage-report
          path: back/target/site/jacoco/

      - name: Publish coverage to Coveralls
        if: always()
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: back/target/site/jacoco/jacoco.xml
          format: jacoco
          flag-name: backend
          parallel: true

      - name: SonarCloud Scan
        if: always()
        run: |
          cd back
          mvn sonar:sonar \
            -Dsonar.token=${SONAR_TOKEN} \
            -Dsonar.projectKey=tangilc_OC-P10_CICD:back \
            -Dsonar.organization=tangilc \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.java.coveragePlugin=jacoco
