name: Docker Build and Run
run-name: ${{ github.actor }} | Docker CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  docker-build-run:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Front-end Docker container
        working-directory: front
        run: docker build -t bobapp-front .

      - name: Run Front-end container
        run: docker run -p 8080:8080 --name bobapp-front -d bobapp-front

      - name: Build Back-end Docker container
        run: |
          cd back
          docker build -t bobapp-back .

      - name: Run Back-end container
        run: docker run -p 8081:8080 --name bobapp-back -d bobapp-back

      - name: List running containers
        run: docker ps
