name: Frontend Build and Test CI
run-name: ${{ github.actor }} | Frontend Build and Test CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'front/**'

  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'front/**'

jobs:
  frontend-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Front-end dependencies
        working-directory: front
        run: npm install

      - name: Install Chrome browser for tests
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Front-end tests with coverage
        working-directory: front
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          npm test -- --browsers ChromeHeadless --watch=false --code-coverage --karma-config karma.conf.js

      - name: Frontend Test Report
        uses: phoenix-actions/test-reporting@v14
        id: front-test-report
        if: always()
        with:
          name: Frontend Tests
          path: front/coverage/bobapp/test-results.xml
          reporter: java-junit

      - name: Upload front-end coverage report
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage-report
          path: front/coverage/bobapp

      - name: SonarCloud Scan
        uses: Sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=tangilc_OC-P10_CICD:front
            -Dsonar.organization=tangilc
            -Dsonar.sources=src
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts,**/test.ts,**/karma.conf.js,**/environments/**
            -Dsonar.coverage.exclusions=**/main.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
