name: Deploy BobApp
on:
  workflow_run:
    workflows: ["Frontend Build & Test", "Backend Build & Test"]
    types:
      - completed
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download frontend image
        uses: actions/download-artifact@v4
        with:
          name: frontend-docker-image

      - name: Download backend image
        uses: actions/download-artifact@v4
        with:
          name: backend-docker-image

      - name: Load Docker images
        run: |
          docker load < bobapp-front.tar
          docker load < bobapp-back.tar

      - name: Run containers
        run: |
          docker run -d -p 8080:8080 --name bobapp-front bobapp-front
          docker run -d -p 8081:8080 --name bobapp-back bobapp-back

      - name: Health check
        run: |
          sleep 10  # Wait for containers to start
          curl -f http://localhost:8080/health || exit 1
          curl -f http://localhost:8081/actuator/health || exit 1
