name: SonarCloud | Backend BobApp
run-name: ${{ github.actor }} | SonarCloud Analysis

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd back
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=TangiLC_OC-P10_CICD \
          -Dsonar.qualitygate.wait=true \
          -Dsonar.coverage.exclusions=**/*Application.java \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
          -Dsonar.java.codeCoveragePlugin=jacoco \
          -Dsonar.coverage.ratio > 80% \
          -Dsonar.reliability.rating = A \
          -Dsonar.qualitygate.timeout=300
