name: Build and Test for Sonar Analyze
run-name: ${{ github.actor }} | Full Build for Sonar Analyze

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  frontend-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Front-end dependencies
        working-directory: front
        run: npm install

      - name: Install Chrome browser for tests
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Front-end tests with coverage
        working-directory: front
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          npm test -- --browsers ChromeHeadless --watch=false --code-coverage --karma-config karma.conf.js

      - name: Upload front-end coverage report
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage-report
          path: front/coverage/bobapp/lcov.info

  backend-build-test:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java & Maven
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install back-end dependencies & Run tests with coverage
        run: |
          cd back
          mvn clean verify

      - name: Upload back-end coverage report
        uses: actions/upload-artifact@v4
        with:
          name: back-coverage-report
          path: back/target/site/jacoco/jacoco.xml

  merge-coverage:
    needs: [frontend-build-test, backend-build-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download front-end coverage report
        uses: actions/download-artifact@v4
        with:
          name: front-coverage-report
          path: coverage/front

      - name: Download back-end coverage report
        uses: actions/download-artifact@v4
        with:
          name: back-coverage-report
          path: coverage/back

      - name: Install LCOV tool
        run: sudo apt-get install -y lcov

      - name: Convert JaCoCo XML to LCOV
        run: |
          curl -o jacoco2lcov.py https://raw.githubusercontent.com/jacoco/jacoco/master/scripts/jacoco2lcov.py
          python3 jacoco2lcov.py coverage/back/jacoco.xml --output coverage/back/jacoco.lcov

      - name: Merge LCOV reports
        run: |
          lcov -a coverage/front/lcov.info -a coverage/back/jacoco.lcov -o coverage/merged-coverage.info
          lcov --list coverage/merged-coverage.info

      - name: Upload merged coverage report
        uses: actions/upload-artifact@v4
        with:
          name: merged-coverage-report
          path: coverage/merged-coverage.info

      - name: SonarCloud Scan with Merged Coverage
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=TangiLC_OC-P10_CICD \
            -Dsonar.organization=tangilc \
            -Dsonar.sources=front/src,back/src \
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts,**/test.ts,**/karma.conf.js,**/environments/** \
            -Dsonar.coverage.exclusions=**/main.ts \
            -Dsonar.javascript.lcov.reportPaths=coverage/merged-coverage.info
